name = "transcript-refinery"
main = "src/index.ts"
compatibility_date = "2026-10-04"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "transcript-refinery"
database_id = "4fd2c124-7dcf-42a9-9e65-2ee224113967"
migrations_dir = "migrations"
